version: "3"
services:
    wazuh:
        container_name: wazuh
        image: cyberhackfr/wazuh:0.0.1
        build: .
        hostname: wazuh-manager
        restart: always
        ports:
        - "1514:1514/udp"
        - "1515:1515"
        - "514:514/udp"
        - "55000:55000"
        volumes:
        - /var/lib/cbox/wazuh-authd.pass:/wazuh-config-mount/etc/authd.pass
        env_file:
        - ../../config/secrets/wazuh.conf
        - /etc/cbox/modules.conf
